name = "ExaPowerIO"
uuid = "14903efe-9500-4d7f-a589-7ab7e15da6de"
authors = ["Archim Jhunjhunwala <archimj@mit.edu>"]
version = "0.2.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
Artifacts = "1.11.0"
LazyArtifacts = "1.11.0"
julia = "1.9"
