name = "ExaPowerIO"
uuid = "14903efe-9500-4d7f-a589-7ab7e15da6de"
authors = ["Archim Jhunjhunwala <archimj@mit.edu>"]
version = "0.1.0"

[deps]
PGLib = "07a8691f-3d11-4330-951b-3c50f98338be"

[compat]
PGLib = "0.2.1"
julia = "1.9"
