name = "ExaPowerIO"
uuid = "14903efe-9500-4d7f-a589-7ab7e15da6de"
authors = ["Archim Jhunjhunwala <archimj@mit.edu>"]
version = "0.1.1"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
Artifacts = "1.11.0"
julia = "1.9"
